server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arjoo/spring-cloud-config-storage
          search-paths: '*service'
          
management:
  endpoints:
    web:
      exposure:
        include: '*'
